### Get All Data
GET http://localhost:3000/tasks

### Get Tasks Details
GET http://localhost:3000/tasks/2

### Create Data
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "description": "Belajar Crypto",
    "deadline": "1-04-2024",
    "priority": "3",
    "is_completed": "true"
}

### Update Data
PUT http://localhost:3000/tasks/2
Content-Type: application/json

{
    "description": "Membuat Web Profile",
    "deadline": "29-09-2024",
    "priority": "1",
    "is_completed": "true"
}

### Deleted Data
DELETE http://localhost:3000/tasks/8
